export const citiesEn = [
  {title: 'Riga', value: 'Riga'},
  {title: 'Ainaži', value: 'Ainaži'},
  {title: 'Aizkraukle', value: 'Aizkraukle'},
  {title: 'Aizpute', value: 'Aizpute'},
  {title: 'Aknīste', value: 'Aknīste'},
  {title: 'Aloja', value: 'Aloja'},
  {title: 'Alūksne', value: 'Alūksne'},
  {title: 'Ape', value: 'Ape'},
  {title: 'Auce', value: 'Auce'},
  {title: 'Baldone', value: 'Baldone'},
  {title: 'Baloži', value: 'Baloži'},
  {title: 'Balvi', value: 'Balvi'},
  {title: 'Bauska', value: 'Bauska' },
  {title: 'Brocēni', value: 'Brocēni'},
  {title: 'Cesvaine', value: 'Cesvaine'},
  {title: 'Cēsis', value: 'Cēsis' },
  {title: 'Dagda', value: 'Dagda'},
  {title: 'Daugavpils', value: 'Daugavpils'},
  {title: 'Dobele', value: 'Dobele' },
  {title: 'Durbe', value: 'Durbe'},
  {title: 'Grobiņa', value: 'Grobiņa'},
  {title: 'Gulbene', value: 'Gulbene' },
  {title: 'Ikšķile', value: 'Ikšķile'},
  {title: 'Ilūkste', value: 'Ilūkste'},
  {title: 'Jaunjelgava', value: 'Jaunjelgava' },
  {title: 'Jelgava', value: 'Jelgava'},
  {title: 'Jēkabpils', value: 'Jēkabpils'},
  {title: 'Jūrmala', value: 'Jūrmala' },
  {title: 'Kandava', value: 'Kandava'},
  {title: 'Krāslava', value: 'Krāslava'},
  {title: 'Kuldīga', value: 'Kuldīga' },
  {title: 'Kārsava', value: 'Kārsava'},
  {title: 'Lielvārde', value: 'Lielvārde'},
  {title: 'Liepāja', value: 'Liepāja' },
  {title: 'Limbaži', value: 'Limbaži'},
  {title: 'Lubāna', value: 'Lubāna'},
  {title: 'Ludza', value: 'Ludza' },
  {title: 'Līgatne', value: 'Līgatne'},
  {title: 'Līvāni', value: 'Līvāni'},
  {title: 'Madona', value: 'Madona' },
  {title: 'Mazsalaca', value: 'Mazsalaca'},
  {title: 'Ogre', value: 'Ogre'},
  {title: 'Olaine', value: 'Olaine' },
  {title: 'Piltene', value: 'Piltene'},
  {title: 'Preiļi', value: 'Preiļi'},
  {title: 'Priekule', value: 'Priekule' },
  {title: 'Pāvilosta', value: 'Pāvilosta'},
  {title: 'Pļaviņas', value: 'Pļaviņas'},
  {title: 'Rēzekne', value: 'Rēzekne' },
  {title: 'Rīga', value: 'Rīga'},
  {title: 'Rūjiena', value: 'Rūjiena'},
  {title: 'Sabile', value: 'Sabile' },
  {title: 'Salacgrīva', value: 'Salacgrīva'},
  {title: 'Salaspils', value: 'Salaspils' },
  {title: 'Saldus', value: 'Saldus'},
  {title: 'SaulkrastiMunicipality', value: 'SaulkrastiMunicipality' },
  {title: 'Seda', value: 'Seda'},
  {title: 'Sigulda', value: 'Sigulda'},
  {title: 'Skrunda', value: 'Skrunda' },
  {title: 'Smiltene', value: 'Smiltene'},
  {title: 'Staicele', value: 'Staicele'},
  {title: 'Stende', value: 'Stende' },
  {title: 'Strenči', value: 'Strenči'},
  {title: 'Subate', value: 'Subate'},
  {title: 'Talsi', value: 'Talsi' },
  {title: 'Tukums', value: 'Tukums'},
  {title: 'ValdemārpilsMunicipality', value: 'ValdemārpilsMunicipality' },
  {title: 'Valka', value: 'Valka'},
  {title: 'Valmiera', value: 'Valmiera'},
  {title: 'Vangaži', value: 'Vangaži' },
  {title: 'Varakļāni', value: 'Varakļāni'},
  {title: 'Ventspils', value: 'Ventspils' },
  {title: 'Viesīte', value: 'Viesīte'},
  {title: 'Viļaka', value: 'Viļaka'},
  {title: 'Viļāni', value: 'Viļāni' },
  {title: 'Zilupe', value: 'Zilupe'},
  {title: 'Ķegums', value: 'Ķegums'}
];
