import {initFilters} from "./filters";

export const profileData =  {
  displayName: '',
  dateOfBirth: 0, //929480340000
  birthday: '', //15/06/1999
  country: 'Latvia',
  city: '',
  creationTime: '',
  helloMessage: '',
  gender: '',
  phoneNumber: '',
  lookingFor: [],
  languages: [],
  figure: '',
  height: '',
  ethnicity: '',
  hair: '',
  eyes: '',
  occupation: '',
  interests: '',
  dressStyle: '',
  food: '',
  drinks: '',
  whatYouLikeInSex: '',
  whatYouDontLikeInSex: '',
  areaAvailability: '',
  expectedReward: '',
  iLookLike: '',
  photos: [],
  videos: [],
  mainPhoto: -1,
  role: '',
  lang: 'en',
  hasPhotos: false,
  profileSubmitted: false,
  profileVerified: false,
  approved: false,
  hasSeenNotification: true,
  status: '',
  lastVisit: 0,
  id: '',
  isLoaded: true,
  filters: initFilters,
  showPrivatePhotos: [],
  mfa: false,
  hasDatingRequests: false
};

export const titlesEn = {
  displayName: 'Display Name',
  dateOfBirth: 'Date of Birth',
  country: 'Country',
  city: 'City',
  helloMessage: 'Hello message',
  gender: 'Gender',
  phoneNumber: 'Phone Number',
  lookingFor: 'Looking for',
  languages: 'Languages',
  figure: 'Figure',
  height: 'Height, cm',
  ethnicity: 'Ethnicity',
  hair: 'Hair',
  eyes: 'Eyes',
  occupation: 'Occupation',
  interests: 'Interests',
  dressStyle: 'Dress style',
  food: 'Food',
  drinks: 'Drinks',
  whatYouLikeInSex: 'What I like in sex',
  whatYouDontLikeInSex: `What I don't like in sex`,
  areaAvailability: 'To meet someone I can travel',
  expectedReward: 'A decent gift is worth',
  iLookLike: 'I look like...',
  photos: 'Photos',
  videos: 'Videos',
  mainPhoto: 'Index photo',
  role: 'Role',
  approved: 'Approved',
  withPhotos: 'With photos'
};

export const titlesRu = {
  displayName: 'Имя',
  dateOfBirth: 'Дата рождения',
  country: 'Страна',
  city: 'Город',
  helloMessage: 'Приветствие',
  gender: 'Пол',
  phoneNumber: 'Номер телефона',
  lookingFor: 'Я ищу',
  languages: 'Языки',
  figure: 'Фигура',
  height: 'Рост, см',
  ethnicity: 'Раса',
  hair: 'Цвет волос',
  eyes: 'Цвет глаз',
  occupation: 'В жизни я',
  interests: 'Интересы',
  dressStyle: 'Стиль в одежде',
  food: 'Любимая еда',
  drinks: 'Любимые напитки',
  whatYouLikeInSex: 'В сексе люблю',
  whatYouDontLikeInSex: `В сексе не люблю`,
  areaAvailability: 'Ради встречи могу поехать',
  expectedReward: 'Ожидаемая награда',
  iLookLike: 'Я выгляжу как...',
  photos: 'Фото',
  videos: 'Видео',
  mainPhoto: 'Основная фото',
  role: 'Роль',
  approved: 'Подтверждено',
  withPhotos: 'С фото'
};

export const titlesLv = {
  displayName: 'Parādāmais vārds',
  dateOfBirth: 'Dzimšanas datums',
  country: 'Valsts',
  city: 'Pilsēta',
  helloMessage: 'Sveika ziņa',
  gender: 'Dzimums',
  phoneNumber: 'Telefona numurs',
  lookingFor: 'Meklēju',
  languages: 'Valodas',
  figure: 'Attēls',
  height: 'Augstums,cm',
  ethnicity: 'Etniskā piederība',
  hair: 'Mati',
  eyes: 'Acis',
  occupation: 'Nodarbošanās',
  interests: 'Intereses',
  dressStyle: 'Kleita stils',
  food: 'Ēdiens',
  drinks: 'Dzērieni',
  whatYouLikeInSex: 'Kas man patīk seksā',
  whatYouDontLikeInSex: `Kas man nepatīk seksā`,
  areaAvailability: 'Lai satiktu kādu, es varu ceļot',
  expectedReward: 'Pienācīga dāvana ir vērts',
  iLookLike: 'ES izskatos kā...',
  photos: 'Fotoattēli',
  videos: 'Video',
  mainPhoto: 'Galvenā fotogrāfija',
  role: 'Loma',
  approved: 'Apstiprināts',
  withPhotos: 'Ar foto'
};

export const placeholdersEn = {
  displayName: 'Jennifer',
  dateOfBirth: '03/03/1998',
  country: 'Latvia',
  city: 'Riga',
  helloMessage: 'This message will be visible on your profile in search results. Avoid adding contact info or obscenities',
  gender: 'Woman',
  phoneNumber: '+999 99 999 999',
  lookingFor: 'Man',
  languages: 'English',
  figure: 'Athletic',
  height: '170',
  ethnicity: 'European',
  hair: 'Blonde',
  eyes: 'Blue',
  occupation: 'What you do in life',
  interests: 'What you like and do in your free time',
  dressStyle: 'Sporty or elegant? Maybe vintage?',
  food: 'Italian or Japanese? Ramen or borscht?',
  drinks: 'Wine or beer? Or maybe still water?',
  whatYouLikeInSex: 'Your likes and kinks',
  whatYouDontLikeInSex: 'Your taboos and things that just don’t fancy',
  areaAvailability: 'Only within my city',
  expectedReward: '200',
  iLookLike: 'Uma Turman',
  photos: '',
  videos: '',
  mainPhoto: '',
  role: '',
  approved: '',
};

export const placeholdersRu = {
  displayName: 'Катя',
  dateOfBirth: '03/03/1998',
  country: 'Латвия',
  city: 'Riga',
  helloMessage: 'Это сообщение будет видно на твоей странице и в поиске. Не пиши здесь ругательств или контактных данных',
  gender: 'Женский',
  phoneNumber: '+999 99 999 999',
  lookingFor: 'Мужчину',
  languages: 'Русский',
  figure: 'Атлетическая',
  height: '170',
  ethnicity: 'Европейская',
  hair: 'Светлые',
  eyes: 'Голубые',
  occupation: 'Тренер по фитнесу',
  interests: 'Что делаешь в свободное от работы время',
  dressStyle: 'Спортивный или классический? А может, винтаж?',
  food: 'Итальянская или японская? Рамен или борщ?',
  drinks: 'Вино или пиво? А может, вода без газа?',
  whatYouLikeInSex: 'То что тебя заводит',
  whatYouDontLikeInSex: `Твои табу и просто неприкольные вещи`,
  areaAvailability: 'В пределах моего города',
  expectedReward: '200',
  iLookLike: 'Ума Турман',
  photos: '',
  videos: '',
  mainPhoto: '',
  role: '',
  approved: '',
};

export const placeholdersLv = {
  displayName: 'Beate',
  dateOfBirth: '03/03/1998',
  country: 'Latvija',
  city: 'Riga',
  helloMessage: 'Šis ziņojums būs redzams jūsu profilā meklēšanas rezultātos. Izvairieties pievienot kontaktinformāciju vai neķītrības',
  gender: 'Sieviete',
  phoneNumber: '+999 99 999 999',
  lookingFor: 'Cilvēks',
  languages: 'Angļu',
  figure: 'Atlētisks',
  height: '170',
  ethnicity: 'Eiropas',
  hair: 'Blondīne',
  eyes: 'Zils',
  occupation: 'Ko jūs darāt dzīvē',
  interests: 'Kas jums patīk un ko darāt brīvajā laikā',
  dressStyle: 'Sportisks vai elegants? Varbūt vintage?',
  food: 'Itāļu vai japāņu? Ramena vai borščs?',
  drinks: 'Vīns vai alus? Vai varbūt vēl ūdeni?',
  whatYouLikeInSex: 'Jūsu patīk un kink?',
  whatYouDontLikeInSex: 'Jūsu tabu un lietas, kas vienkārši neiedomājas',
  areaAvailability: 'Tikai manā pilsētā',
  expectedReward: '200',
  iLookLike: 'Uma Turman',
  photos: '',
  videos: '',
  mainPhoto: '',
  role: '',
  approved: '',
};
