import {citiesEn} from "../constants/citiesEn";
import {countriesEn, countriesRu} from "../constants/countries";
import {placeholdersEn, placeholdersRu, titlesEn, titlesLv, titlesRu} from "../constants/profile";
import {
  adaptiveLocationOptionsEn,
  adaptiveLocationOptionsLv, adaptiveLocationOptionsRu,
  areaAvailabilityOptionsEn, areaAvailabilityOptionsLv, areaAvailabilityOptionsRu,
  ethnicityOptionsEn,
  ethnicityOptionsLv,
  ethnicityOptionsRu,
  eyesOptionsEn,
  eyesOptionsLv,
  eyesOptionsRu,
  figureOptionsEn,
  figureOptionsLv,
  figureOptionsRu,
  genderOptionsEn,
  genderOptionsLv,
  genderOptionsRu,
  hairOptionsEn,
  hairOptionsLv,
  hairOptionsRu,
  languagesOptionsEn,
  languagesOptionsLv,
  languagesOptionsRu, locationOptionsEn, locationOptionsLv, locationOptionsRu,
  lookingForOptionsEn,
  lookingForOptionsLv,
  lookingForOptionsRu, privacyLevelEn, privacyLevelLv, privacyLevelRu
} from "../constants/selectOptions";
import {faqEn, faqRu, faqLv, faqMenLv, faqMenRu, faqMenEn} from "../constants/faq";
import {
  cookiePolicyEn,
  intellectualPropertyEn,
  safetyPolicyEn,
  safetyTipsEn,
  termsConditionsEn
} from '../constants/regulations-list';

const localisation = {
  en:{
    clarification: "Paid dating service from 2022",
    signIn: "Log in",
    signUp: "Sign up",
    paidService: "Paid dating existed before Egyptian pyramids. It will exist after the World War VIII that kills 90% of the world population in year 5042.",
    weAreWorking: "We’re working on making this service perfect and will be ready for launch in early 2021. Become our early member and get a nice bonus on launch!",
    addYourProfile: "Add your profile",
    inventIt: "We didn’t invent it.",
    weMadeItTransparent: "We made it transparent, safe and pleasant.",
    wantToGetPartner: "Want to find a partner for a safe and profitable affair?",
    menWantToGetPartner: "Do you want to find a girl for easy dating?",
    iLookingFor: "I’m looking for",
    howItWorkedBefore: "How it worked before",
    lookingForAPartner: "Looking for a partner on a “normal” dating platform",
    struggleWithShyness: "Struggle with shyness",
    tryToFilter: "Try to filter out 80% of scam offers",
    hopeThat: "Hope that this guy or girl really looks like that",
    tryYourBest: "Try your best not to be banned",
    or: "or",
    browseUnpleasantWebsites: "Browse unpleasant websites in 90s style",
    messWithShadyGuys: "Mess with shady guys",
    thatThePhotosAreReal: "Don’t even hope that the photos are real",
    neverSeeYourPartner: "Never see your partner before you meet",
    workWithCash: "Work with cash and pray you get outta there safe",
    howItWorksOn: "How it works on",
    allUsersHaveClearIntentions: "All users have clear intentions and won’t get you wrong",
    noEscort: 'No escort agencies and fakes, only real girls from Latvia',
    uploadedPhotosAreVerified: "Uploaded photos are verified",
    yourIdentity: "Your identity is never revealed to public",
    decideWhomToChatWith: "Decide whom to chat with",
    hideYourPhotos: "Hide your photos and show to selected users",
    payAndGetPaid: "Pay and get paid via cash or bank card securely",
    joinLayNow: "Join Lay now!",
    faq: "FAQ",
    comingSoon: "Coming soon",
    paidDatingService: "Paid dating service",
    welcomeToLay: 'Welcome to Lay!',
    signInWithGoogle: 'Sign in with Google',
    submitYourEmail: 'Submit your email',
    emailIsIncorrect: 'Email is incorrect',
    emailAlreadyInUse: 'Email is already on use',
    createPasswordLabel: 'Create a password',
    wrongPassword: 'Wrong password',
    tooManyRequests: 'Too many requests',
    userNotFound: 'User not found',
    createPasswordErrorText: 'The password must have at least 1 lowercase leer, 1 uppercase letter, 1 digit and total at least 8 symbols',
    confirmPasswordsLabel: 'Confirm passwords',
    confirmPasswordsError: 'Passwords don’t match',
    continueButton: 'Continue',
    bySigningUpIAgreeTo: 'By registering, I agree with the documents:',
    termsOfService: 'terms of service',
    privacyPolicy: 'privacy policy',
    and: 'and',
    alreadyGotAnAccount: 'Already got an account?',
    logIn: 'Log in',
    welcomeBack: 'Welcome back!',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    incorrectUsernameOrPassword: 'Incorrect username or password',
    forgotPassword: 'Forgot password?',
    submitYourEmailText: 'Submit your email, we’ll send you a link to restore password',
    sentAResetPassword: 'We have sent a reset password link to',
    proceedToYourInbox: 'Please proceed to your inbox.',
    chooseYourRole: 'Please choose your role on Lay',
    patronLabel: 'Sponsor',
    patronText: 'You reward Favourites for the dates.',
    favoriteLabel: 'Favorite',
    favoriteText: 'Sponsors reward you for the dates.',
    thankYou: 'Thank you for adding your beautiful profile on Lay',
    thankYouText: 'Lay will be launched later this autumn. Become our early member and get a bonus!',
    layTeam: 'Yours, Lay team',
    success: 'Success!',
    confirmYourEmail: 'Please go to your inbox and confirm your email hitting a link we sent you.',
    sendAgainText: 'Didn\'t receive the Email?',
    sendAgainTextCaption: 'Emails are normally delivered within 1-2 minutes but it can take up to 5 minutes. Also please check your Spam folder, verification emails might be there. Should you have any problems, contact us via support@lay.ooo',
    sendAgainLink: 'Send it Again',
    personalInformation: 'Personal information',
    personalInfoTitles: titlesEn,
    personalInfoPlaceholders: placeholdersEn,
    submitPersonalNumber: 'Your phone number won’t be visible to other users. It’s needed to verify your profile. Please submit your personal number.',
    addPersonalNumber: 'Please add your phone number. It will  <strong>never</strong> be available to the Lay' +
      ' users. Admins need it to' +
      ' verify your profile but will  <strong>never disclose</strong> it to anyone. We value your privacy and at' +
      ' the same time need' +
      ' all Lay users to be real people.',
    yourPhoneIsProtected: 'Your phone number is protected by General Data Protection Regulation (GDPR), a regulation in the European Union law. You are able to request a complete deletion of all your personal information on Lay contacting us on support@lay.ooo.',
    completeMandatoryField: 'Mandatory field. Please fill in',
    displayNameLengthError: 'Minimum name\'s length is 2 symbols, letters only accepted',
    phoneNumberIsNotCorrect: 'Phone number isn\'t correct',
    dateIsNotCorrect: 'Lay is not for those who’s younger than 18',
    countries: countriesEn,
    next: 'Next',
    submit: 'Submit',
    tellAboutYourself: 'Tell other people about yourself. All fields are not mandatory, you can skip it for now and add later if you want. Please don’t use strong language or leave any contacts (telephone, email, website, messenger ID, address). Your account will be suspended otherwise.',
    tellAboutYourSecrets: 'Tell people about your secrets. This information is not public: you’ll need to unlock this section of your profile to a user personally, while chatting. If you trust them enough.',
    secretsAlert: 'Information from this section will not be publicly available. <strong>Nobody</strong> will see it' +
      ' on Lay' +
      ' website.',
    photoAlert: 'You can make your photos private so nobody will see them on your profile page on Lay.',
    whyAddPhoto: 'Why add photos? To increase your chances for a successful date 🙂 76% of $gender on Lay add photos' +
      ' of' +
      ' themselves - their profiles are viewed more frequently and more people start chats with them. If you don’t want to disclose your personality, just choose <strong>Private</strong> option. In this case other people will see that you’ve got private photos and will ask your permission to view them, in the Lay Chat. Then you decide whether you want to give access or not 😉',
    addInfoAboutYourSecrets: 'Add information about your sex preferences, gift expectations and travel' +
      ' opportunities.  It <strong>won’t be shown</strong> on your profile page on Lay. You will be able to' +
      ' open this' +
      ' section' +
      ' to another person privately in the <strong>Lay Chat</strong>. There will be a special button for that.',
    whyAddInfoAboutYourSecrets: 'Why add this anyway? For your future convenience :) These questions are quite' +
      ' frequently asked, and having all this stuff in one place being able to share with 1 click will just make your life easier. No useless talks and same things explained again and again. You will be able to edit this anytime.',
    noteThatBeforeModerator: 'Please note that your photos will be verified by a moderator. You can mark your photos as private: they won’t be shown publicly but you will be able to reveal them to another user. Alternatively, you can restrict them to be seen by moderators only.',
    uploadUpPhotos: 'Upload up to 10 photos of yourself in real life. Make sure that at least one of these photos contains your face clearly visible - it is needed for verification. If you want you can limit public access to the photos with your face.  Nude photos are OK but you cannot make them public.',
    addPhoto: '+ Add photo',
    addLink: '+ Add link',
    pasteLinks: 'Paste links to your Youtube or TikTok videos. Nude videos are prohibited.',
    photosTitle: 'Photos',
    videosTitle: 'Videos',
    tabsTitles: [
      {
        label: '1. Index',
        disabled: false
      },
      {
        label: '2. About you',
        disabled: false
      },
      {
        label: '3. Secrets',
        disabled: false
      },
      {
        label: '4. Photos',
        disabled: false
      },
    ],
    citiesTitles: citiesEn,
    genderOptions: genderOptionsEn,
    lookingForOptions: lookingForOptionsEn,
    languagesOptions: languagesOptionsEn,
    figureOptions: figureOptionsEn,
    ethnicityOptions: ethnicityOptionsEn,
    hairOptions: hairOptionsEn,
    eyesOptions: eyesOptionsEn,
    areaAvailabilityOptions: areaAvailabilityOptionsEn,
    faqList: faqEn,
    faqMenList: faqMenEn,
    modalPhoneTitle: 'Seems you forgot your phone number',
    modalPhoneBtnLeft: 'Continue without a phone number',
    modalPhoneBtnRight: 'Get back and add a phone number',
    modalPhoneContent: ['It’s a pity that you would like to register without a phone number. In this case we won’t' +
    ' be able to confirm that you’re a real person.', 'What’s gonna happen now? Profiles that were added without' +
    ' submitting a phone number will be shown less than verified profiles. 72% of Lay users submitted their numbers' +
    ' so the rest 28% will be at the bottom of the list 🙁', 'What can I do? Go back and add your phone 🙂 Or at least' +
    ' add some photos on the next stage. Profiles with photos, even with private ones, will be shown more times than those who have neither a phone number nor a photo.'],
    editForm: 'Edit profile',
    termsConditionsTitle: 'TERMS AND CONDITIONS OF USE',
    termsConditionsList: termsConditionsEn,
    safetyTipsTitle: 'DATING SAFETY TIPS',
    safetyTipsList: safetyTipsEn,
    safetyPolicyTitle: 'SAFETY POLICY TERMS AND CONDITIONS',
    safetyPolicyList: safetyPolicyEn,
    intellectualPropertyTitle: 'INTELLECTUAL PROPERTY TERMS',
    intellectualPropertyList: intellectualPropertyEn,
    cookiePolicyTitle: 'COOKIE POLICY',
    cookiePolicyList: cookiePolicyEn,
    firstChatPopupTitle: 'Before you start chatting...',
    firstChatPopupFirstText: 'We maintain a friendly environment on Lay and don\'t let users be rude to each other. Please respect the others and talk in a polite manner. Keep in mind that there\'s a Report button in the chat which both parties of the chat can use. Our team will review all the reports and will have to ban those who violate the rules. Hope this will never happen to you',
    firstChatPopupSecondText: 'Love, Lay team',
    firstChatPopupButton: 'OK, got it!',
    firstChatPopupMessagesTitle: 'Welcome to your first chat!',
    firstChatPopupMessagesFirstText: 'Check the 3 dot button on the right. There you can:',
    firstChatPopupMessagesOptions: ['Block or report user', 'Delete chat'],
    firstChatPopupMessagesPs: 'PS: if you decide to meet each other, please don’t forget to «Offer a date» or accept an offer. In this case we’ll be able to help you if you have any misunderstanding.',
    notApprovedPopupTitle: 'Thanks for registering on Lay!',
    notApprovedPopupText: 'Now your profile is under review by our admins and other users don’t see you. While the approval is in progress, you can use search and see other people. After we approve you, your profile becomes visible to others. You will also be able to contact people and publish promos about yourself for free. We’ll notify you via email!',
    dialogOptions: {
      block : {
        head: 'Are you sure?',
        content: 'After blocking $displayName won’t be able to you messages and you won’t be able to reply. You' +
          ' will be able to unblock this person in the future.',
        leftBtnText: 'Yes',
        rightBtnText: 'Cancel'
      },
      report : {
        head: 'Are you sure?',
        content: 'After receiving this report our support team will review it, contact you and probably block $displayName.',
        leftBtnText: 'Yes',
        rightBtnText: 'Cancel'
      },
      remove : {
        head: 'Are you sure?',
        content: 'All your messaging history will be removed and you won’t be able to restore it.',
        leftBtnText: 'Yes',
        rightBtnText: 'Cancel'
      },
    },
    location: locationOptionsEn,
    adaptiveLocation: adaptiveLocationOptionsEn,
    whyLocation: 'Let people know where do you plan to meet them. You can choose multiple options.',
    roles: {
      title: 'Are you sure?',
      leftBtnText: 'Yes, I’m sure 😉',
      rightBtnText: 'Oh no',
      content: 'In Lay we’re totally for the gender equality but just for your information: 96% of men signing up choose Sponsor role while 97% of girls choose Favorite role. As a Favorite you’ll see mostly men who’re looking for paid dates with girls.'
    },
    deletePopup: {
      title: 'Are you sure?',
      leftBtnText: 'Yes, I’m sure',
      rightBtnText: 'Oh no'
    },
    profileNavTitles: ['Profile', 'Search people', 'Chats', 'Search dates'],
    addADateRequest: 'Promote myself',
    profileOptions: ['Add a promo', 'Edit Profile', 'Logout', 'Settings'],
    chatNow: 'Chat now',
    lastVisitText: 'Last seen $lastVisit',
    profileTabs: ['About me', 'Secrets', 'Promo', 'Dates'],
    requestsTableTitles: {
      location: 'Location',
      date: 'Date',
      time: 'Time',
      published: 'Published',
      chats: 'Chats',
      expires: 'Expires',
      with: 'With',
      gift: 'Gift',
      preferredDateText: 'Preferred date',
      preferredTimeText: 'Preferred time',
    },
    edit: 'Edit',
    publishAgain: 'Publish again',
    goToChat: 'Go to chat',
    alertPhotos: 'The eye icon shows a photo’s visibility. Public photos are shown on your page while private are revealed\n' +
      ' manually in a chat.',
    yourPhotos: 'Your photos',
    searchFilters: 'Search filters',
    save: 'Save',
    expired: 'Expired',
    startChat: 'Start a chat to ask for a permission to view',
    morePrivatePhoto: '1 more private photo',
    morePrivatePhotos: '$count more private photos',
    textFieldLabels: {
      tagline: 'Tagline',
      description: 'Description',
      comments: 'Comments',
      startDate: 'Start date',
      date: 'Date',
      endDate: 'End date',
      preferredStartTime: 'Preferred start time',
      preferredEndTime: 'Preferred end time',
    },
    textFieldPlaceholders: {
      myHome: 'My home',
      lookingForward: 'Looking forward to meet you!',
      dateRequestTitle: 'This will be displayed in the list of date requests as a title',
      dateRequestDescription: 'Briefly describe what you expect from a date',
      chatInput: 'Type your message here',
      oldPassword: 'Old password',
      newPassword: 'New password',
      confirmPassword: 'Repeat new password',
      phoneNumber: 'Phone number'
    },
    textFieldErrorText: {
      required: 'Required field',
      password: 'Invalid password',
      smthWrong: 'Something wrong'
    },
    done: 'Done',
    cancel: 'Cancel',
    editRequests: 'Edit promo:',
    deletePromo: 'Delete promo',
    mainProfilePhoto: 'Index profile photo',
    privacyLevel: 'Privacy level',
    privacyLevelOptions: privacyLevelEn,
    descriptionText: 'Description',
    whenToMeet: 'When would you like to meet? Note that you can request a date not later than 1\n' +
      '          week from now. You can leave it blank if it’s not critical for you - in this case\n' +
      '          the request will be valid for 2 weeks from now.',
    publish: 'Publish',
    chatRequest: 'Chat request',
    showPrivatePhotosText: 'Show private photos',
    shareText: 'Share',
    photosText: 'photos',
    secretsText: 'secrets',
    wasBlocked: 'was blocked',
    wasUnblocked: 'was unblocked',
    yourDate: 'Your date',
    offerDate: 'Offer date',
    selectChat: 'Please select a chat',
    unblockUserText: 'Unblock user',
    blockUserText: 'Block user',
    reportText: 'Report',
    deleteChatText: 'Delete chat',
    deleteText: 'DELETE',
    doYouWantDeleteMsg: 'Do you want to delete this message?',
    alsoDeleteFor: 'Also delete for',
    actionChatAcceptedText: 'Chat request was accepted',
    actionChatDeclinedText: 'Chat request was declined',
    actionDateOfferAcceptedText: 'Date offer was accepted',
    actionDateOfferDeclinedText: 'Date offer was declined',
    actionDateOfferCanceledText: 'Date offer was canceled',
    wantsToChat: '$name wants to chat with you!',
    accept: 'Accept',
    decline: 'Decline',
    dateRequestText: 'Date request:',
    offersADate: '$name offers a date:',
    youHaveSharedPhotos: 'You have shared $photos $and $secrets with $name',
    sharedPrivatePhotosWithYou: '$name shared $private $photos $and $secrets with you',
    privateText: 'private',
    toMeet: 'To meet',
    submitDateDetails: 'Please submit date details:',
    expectedGift: 'Expected gift',
    specifyDecentGift: 'Specify what a decent gift is worth. You could add a specific amount (100) or a range' +
      ' (100-150) or leave it blank if you prefer to discuss this in person.',
    sendOffer: 'Send offer',
    submitReport: 'Submit report',
    describeWhatWrong: 'Please describe what is wrong:',
    wantToCancelDate: 'Are you sure you want to cancel this date?',
    fundsReleasedBack: 'Held funds will be released back to the Sponsor’s account.',
    yesCancelDate: 'Yes, cancel date',
    noCancelDate: 'No, don’t cancel',
    communicateRegarding: 'Please, for your safety, communicate regarding your date in Lay chat only and meet at the' +
      ' time you agreed to.',
    cancelDateText: 'Cancel a date',
    saveChanges: 'Save changes',
    reset: 'Reset',
    apply: 'Apply',
    sentChatRequest: 'You sent a chat request. $displayName will review it and either accept or reject. It might' +
      ' take some time. In the meantime, you might want to send more chat requests with other people',
    privatePhotoCaption: 'Nobody sees this photo on your page. You can reveal it personally in the chat',
    publicPhotoCaption: 'All users can see this photo on your page',
    age: 'Age',
    changePasswordText: 'Change password',
    changeLanguageText: 'Change language',
    noPromoTitle: 'No promo added so far',
    noPromoText: 'Let people know when and where would you like to meet and we’ll show this ad to others for free!',
    noPromoBtnText: 'Cool! Try now',
    noDatesTitle: 'No dates so far',
    noDatesText: 'We’ll list all your past and future dates here, so you never miss anything!',
    noDatesBtnText: 'Go find someone to date',
    getCode: 'To get the code',
    typeCode: 'Enter a code',
    enable: 'Enable',
    disable: 'Disable',
    successText: 'Success',
    mfaText: 'Multi-factor authentication',
    disableMfa: 'Disable multi-factor authentication',
    enableMfa: 'Enable multi-factor authentication',
    noSelectedPhotos: 'You have not selected any photos',
    returnText: 'Return',
    rowsPerPageText: 'Rows per page',
    ofText: 'of',
    photosDestroyedText: 'Photos will be destroyed in $count seconds',
    fewDetails: '$displayName hasn\'t added any more details. Feel free to ask in chat!',
    soEmpty: 'Your page looks sooo empty! Consider adding some more details',
    noPhotoTitleText: 'No photos at all?',
    noPhotoText: 'If you don’t want to share your real photos, don’t worry. On Lay you can add them in a private' +
      ' mode. Nobody will see them until you share them with a specific person in a chat. Shortly after that private photos are removed from the chat automatically.',
    noPhotoBtnText: 'OK, lemme add some!',
    JustOnePhoto: 'Just one photo?',
    JustOnePhotoBtnText: 'OK, lemme add more!',
    peopleInCity: 'People in your city',
    seeMoreText: 'See more',
    backToProfile: 'Back to profile'
  },
  ru: {
    clarification: "Свидания за деньги из 2022-го",
    signIn: "Вход",
    signUp: "Регистрация",
    paidService: "Свидания за деньги существовали до египетских пирамид. Они продолжат существовать после того, как 8-я Мировая война уничтожит 90% населения Земли в 5042 году.",
    weAreWorking: "Мы работаем над нашим сервисом и будем готовы к запуску в начале 2021-го. Добавь свою анкету уже сейчас, чтобы получить бонус!",
    addYourProfile: "Добавить свой профиль",
    inventIt: "Не мы изобрели их.",
    weMadeItTransparent: "Но мы сделали их прозрачными, безопасными и приятными.",
    wantToGetPartner: "Хочешь найти партнера для безопасных и выгодных встреч?",
    menWantToGetPartner: "Хочешь найти девушку для лёгкого знакомства?",
    iLookingFor: "Я ищу",
    howItWorkedBefore: "Как это работало раньше",
    lookingForAPartner: "Ищешь партнёра на “нормальном” сайте знакомств",
    struggleWithShyness: "Стесняешься, что тебя не так поймут",
    tryToFilter: "Пытаешься отсеять 80% мошенников",
    hopeThat: "Надеешься, что этот парень или девушка выглядят как на фото",
    tryYourBest: "Стараешься, чтобы тебя не забанили",
    or: "или",
    browseUnpleasantWebsites: "Ходишь на уродливые сайты в стиле 90-х",
    messWithShadyGuys: "Делаешь заказ у мутных людей",
    thatThePhotosAreReal: "Даже не надеешься, что фото настоящие",
    neverSeeYourPartner: "Никогда не видишь партнера до свидания",
    workWithCash: "Платишь наличкой и молишься, чтобы выбраться оттуда",
    howItWorksOn: "Как это работает на",
    allUsersHaveClearIntentions: "У всех пользователей понятные цели, все поймут тебя правильно",
    noEscort: 'Никаких эскорт-агентств и фейков, только реальные девушки из Латвии',
    uploadedPhotosAreVerified: "Все загружаемые фотографии верифицируются",
    yourIdentity: "Твоя личность остаётся в секрете",
    decideWhomToChatWith: "Ты выбираешь, с кем общаться и с кем нет",
    hideYourPhotos: "Можешь скрыть свои фото и показывать избранным людям",
    payAndGetPaid: "Можно платить как наличкой, так и картой",
    joinLayNow: "Добавить анкету сейчас!",
    faq: "FAQ",
    comingSoon: "Скоро запуск!",
    paidDatingService: "Сервис свиданий за деньги",
    welcomeToLay: 'Добро пожаловать в Lay!',
    signInWithGoogle: 'Зарегистрироваться через Google',
    submitYourEmail: 'Твой email',
    emailIsIncorrect: 'Email некорректный',
    emailAlreadyInUse: 'Email уже существует',
    createPasswordLabel: 'Придумай пароль',
    wrongPassword: 'Неправильный пароль',
    tooManyRequests: 'Слишком много запросов',
    userNotFound: 'Пользователь не найден',
    createPasswordErrorText: 'Пароль должен иметь минимум 8 символов, из них как минимум одну строчную, одну Заглавную и одну цифру',
    confirmPasswordsLabel: 'Твой пароль ещё раз',
    confirmPasswordsError: 'Пароли не совпадают',
    continueButton: 'Продолжить',
    bySigningUpIAgreeTo: 'Регистрируясь, я соглашаюсь со следующими документами:',
    termsOfService: 'правила пользования',
    privacyPolicy: 'политика конфиденциальности',
    and: 'и',
    alreadyGotAnAccount: 'Уже есть аккаунт?',
    logIn: 'Войти',
    welcomeBack: 'Давно не виделись!',
    emailLabel: 'Email',
    passwordLabel: 'Пароль',
    incorrectUsernameOrPassword: 'Некорректный email или пароль',
    forgotPassword: 'Забыли пароль?',
    submitYourEmailText: 'Укажи свой email, отправим ссылку для восстановления доступа',
    sentAResetPassword: 'Мы отправили ссылку для восстановления на',
    proceedToYourInbox: 'Проверь свои Входящие в почте',
    chooseYourRole: 'Выбери свою роль',
    patronLabel: 'Спонсор',
    patronText: 'Ты будешь вознаграждать Фаворитов за встречи',
    favoriteLabel: 'Фаворит',
    favoriteText: 'Спонсоры будут вознаграждать тебя за встречи',
    thankYou: 'Спасибо за добавление своего прекрасного профиля на Lay',
    thankYouText: 'Lay запустится позже этой осенью. Добавь профиль уже сейчас, чтобы получить бонус!',
    layTeam: 'С уважением, команда Lay',
    success: 'Ура!',
    confirmYourEmail: 'Проверь почту и подтверди свой email, просто нажав на ссылку в письме.',
    sendAgainText: 'Не получили письмо?',
    sendAgainTextCaption: 'Письма для подтверждения обычно доставляются за 1-2 минуты, но это может занять до 5 минут в некоторых случаях. Также пожалуйста проверь папку «Спам», письмо может быть там. Если что-то пошло не так, пиши нам на support@lay.ooo',
    sendAgainLink: 'Отправить повторно',
    personalInformation: 'О тебе',
    personalInfoTitles: titlesRu,
    personalInfoPlaceholders: placeholdersRu,
    submitPersonalNumber: 'Твой телефон никто не увидит, но он нужен для подтверждения профиля. Пожалуйста, добавь личный мобильный номер',
    addPersonalNumber: 'Добавь свой номер телефона. Он <strong>не будет</strong> показан пользователям на Lay. Нашим' +
      ' администраторам он нужен, чтобы подтвердить твою личность, но они <strong>никому</strong> его не раскроют.' +
      ' Мы уважаем твою приватность и в то же время хотим, чтобы на Lay были только реальные профили.',
    yourPhoneIsProtected: 'Твой телефон защищен Законом о защите персональных данных Евросоюза (GDPR). Ты сможешь запросить у нас полное удаление своих данных, обратившись на support@lay.ooo.',
    completeMandatoryField: 'Обязательное поле. Пожалуйста, заполните',
    displayNameLengthError: 'Минимальная длина имени - 2 символа, только буквы',
    phoneNumberIsNotCorrect: 'Номер некорректный',
    dateIsNotCorrect: 'Lay не для тех, кому меньше 18',
    countries: countriesRu,
    next: 'Далее',
    submit: 'ОК',
    tellAboutYourself: 'Расскажи о себе. Все поля необязательные, можешь заполнить их позже. Пожалуйста, не используй ругательства и не оставляй никаких контактов (телефон, email, адрес, ID в мессенджере), иначе нам придется заблокировать аккаунт',
    tellAboutYourSecrets: 'Расскажи о своих секретах - эта информация непубличная, но ты сможешь открыть её из чата персонально для человека, которому доверяешь',
    secretsAlert: 'Информация из этого раздела не будет публично доступной. <strong>Никто</strong> не увидит её на сайте Lay.',
    photoAlert: 'Ты можешь сделать свои фото приватными, чтобы никто не видел их на твоём профиле Lay.',
    whyAddPhoto: 'Зачем добавлять фотки? Чтобы поднять твои шансы на успешное свидание! 76% $gender на Lay добавляют' +
      ' фотографии, их профили чаще просматривают и больше людей пишут им в чат. Если ты не хочешь раскрывать свою' +
      ' личность на публике, просто пометь фото как <strong>приватное</strong>. В этом случае другие люди будут' +
      ' видеть, что у тебя есть фотки, но для их просмотра нужно твоё разрешение. Далее ты решаешь, давать разрешение или нет 😉',
    addInfoAboutYourSecrets: 'Добавь информацию о своих предпочтениях в сексе, ожидания от подарков спонсора и' +
      ' возможность путешествовать. Этой информации <strong>не будет</strong> на странице твоего профиля на Lay. Ты' +
      ' сможешь' +
      ' открыть этот раздел персонально для другого пользователя через <strong>чат Lay</strong> - будет специальная' +
      ' кнопка для этого.',
    whyAddInfoAboutYourSecrets: 'Зачем вообще это добавлять? Для твоего же удобства 🙂 Эти вопросы постоянно задают, и иметь ответы на них в одном месте, чтобы затем в 1 клик открыть доступ по желанию - это всё облегчит твою жизнь. Никаких бессмысленных разговоров и объяснений одних их тех же вещей по многу раз. Ты сможешь всегда отредактировать эту инфу.',
    noteThatBeforeModerator: 'Твои фотографии будет утверждать модератор. Ты можешь пометить фото как приватные: тогда они не будут показываться на твоей странице, но ты сможешь открыть их персонально в процессе общения с другим пользователем. Также ты можешь закрыть фото полностью, оставив доступ только для модераторов.',
    uploadUpPhotos: 'Загрузите до 10 фотографий себя в реальной жизни. Убедитесь, что хотя бы на одной из этих' +
      ' фотографий ваше лицо хорошо видно - это нужно для проверки. При желании вы можете ограничить публичный' +
      ' доступ к фотографиям с вашим лицом. Обнаженные фотографии - это нормально, но вы не можете сделать их' +
      ' публичными',
    addPhoto: '+ Добавить фото',
    addLink: '+ Добавить ссылку',
    pasteLinks: 'Вставь ссылки из Youtube или TikTok. Обнажённые видео запрещены.',
    photosTitle: 'Фотографии',
    videosTitle: 'Видео',
    tabsTitles: [
      {
        label: '1. Основное',
        disabled: false
      },
      {
        label: '2. О тебе',
        disabled: false
      },
      {
        label: '3. Секреты',
        disabled: false
      },
      {
        label: '4. Фото',
        disabled: false
      },
    ],
    citiesTitles: citiesEn,
    genderOptions: genderOptionsRu,
    lookingForOptions: lookingForOptionsRu,
    languagesOptions: languagesOptionsRu,
    figureOptions: figureOptionsRu,
    ethnicityOptions: ethnicityOptionsRu,
    hairOptions: hairOptionsRu,
    eyesOptions: eyesOptionsRu,
    areaAvailabilityOptions: areaAvailabilityOptionsRu,
    faqList: faqRu,
    faqMenList: faqMenRu,
    modalPhoneTitle: 'Кажется, ты забыл(-a) оставить телефон',
    modalPhoneBtnLeft: 'Продолжить без телефона',
    modalPhoneBtnRight: 'Вернуться и оставить телефон',
    modalPhoneContent: ['Жаль, что ты хочешь зарегистрирвоаться без указания телефона. Мы не сможем убедиться, что' +
    ' ты - реальный человек.', 'Что теперь будет? Профили, зарегистрированные без телефона, мы будем показывать пользователям реже, чем подтвержденные профили. 72% пользователей Lay указывают номер, и 28% неподтвержденнх анкет будут в самом конце списка 🙁', 'Что можно сделать? Добавить свой телефон 🙂 Или хотя бы добавить одну или несколько фото на следующем шаге - профили с фото, даже если они приватные и скрыты ото всех, будут выше профилей, где нет ни телефона, ни фото.'],
    editForm: 'Редактировать профиль',
    termsConditionsTitle: 'TERMS AND CONDITIONS OF USE',
    termsConditionsList: termsConditionsEn,
    safetyTipsTitle: 'DATING SAFETY TIPS',
    safetyTipsList: safetyTipsEn,
    safetyPolicyTitle: 'SAFETY POLICY TERMS AND CONDITIONS',
    safetyPolicyList: safetyPolicyEn,
    intellectualPropertyTitle: 'INTELLECTUAL PROPERTY TERMS',
    intellectualPropertyList: intellectualPropertyEn,
    cookiePolicyTitle: 'COOKIE POLICY',
    cookiePolicyList: cookiePolicyEn,
    firstChatPopupTitle: 'Прежде чем вы начнете общаться...',
    firstChatPopupFirstText: 'Мы поддерживаем на Lay дружелюбную атмосферу, и не приемлем, если кто-то из пользователей начинает грубить. Пожалуйста, уважай других людей и общайся вежливо. Помни, что в чате есть кнопка "Пожаловаться", доступная обоим участникам. Наша команда будет рассматривать все жалобы, и будет вынуждена банить тех, кто нарушает правила. Надеемся, с тобой такого никогда не будет',
    firstChatPopupSecondText: 'С любовью, команда Lay',
    firstChatPopupButton: 'ОК, понятно!',
    firstChatPopupMessagesTitle: 'Добро пожаловать в ваш первый чат!',
    firstChatPopupMessagesFirstText: 'Обратите внимание на кнопку с 3 точками справа. Там вы можете:',
    firstChatPopupMessagesOptions: ['Заблокировать или пожаловаться на пользователя', 'Удалить чат'],
    firstChatPopupMessagesPs: 'PS: Если вы решили встретиться, не забудьте «Предложить свидание» или принять предложение. В этом случае мы сможем вам помочь, если у вас возникнут недоразумения.',
    notApprovedPopupTitle: 'Спасибо за регистрацию на Lay!',
    notApprovedPopupText: 'Сейчас твой профиль находится на рассмотрении у наших администраторов, и другие пользователи тебя не видят. Пока идёт процесс одобрения, ты сможешь пользоваться поиском и видеть других людей. После того, как мы тебя одобрим, твой профиль будет виден другим, а кроме того, ты сможешь писать кому захочешь и размещать промо о себе (это бесплатно!). Мы пришлём тебе email с уведомлением.',
    dialogOptions: {
      block : {
        head: 'Точно?',
        content: 'После блокировки $displayName не сможет отправлять тебе сообщения, и ты не сможешь писать в ответ.' +
          ' Ты' +
          ' сможешь разблокировать этого человека в будущем.',
        leftBtnText: 'Да',
        rightBtnText: 'Отмена'
      },
      report : {
        head: 'Точно?',
        content: 'После получения жалобы наша служба поддержки рассмотрит ее и возможно заблокирует $displayName.',
        leftBtnText: 'Да',
        rightBtnText: 'Отмена'
      },
      remove : {
        head: 'Точно?',
        content: 'Вся история переписки будет удалена без возможности восстановления.',
        leftBtnText: 'Да',
        rightBtnText: 'Отмена'
      },
    },
    location: locationOptionsRu,
    adaptiveLocation: adaptiveLocationOptionsRu,
    whyLocation: 'Сообщите людям, где вы планируете встретиться. Вы можете выбрать несколько вариантов.',
    roles: {
      title: 'Точно?',
      leftBtnText: 'Да, точно 😉',
      rightBtnText: 'Нет, ошибся!',
      content: 'Мы в Lay выступаем за равенство полов, но хотим сообщить тебе, что 96% мужчин выбирают роль Sponsor, а 97% девушек - роль Favorite. Выбрав роль Фаворита, ты будешь видеть только Спонсоров, то есть большинство будут мужчины, ищущие встреч с девушками за вознаграждение.'
    },
    deletePopup: {
      title: 'Точно?',
      leftBtnText: 'Да, точно',
      rightBtnText: 'Нет, ошибся!'
    },
    profileNavTitles: ['Профиль', 'Поиск людей', 'Чаты', 'Поиск знакомств'],
    addADateRequest: 'Прорекламируй себя',
    profileOptions: ['Прорекламируй себя', 'Изменить профиль', 'Выйти', 'Настройки'],
    chatNow: 'Написать',
    lastVisitText: 'Заходил(-a) $lastVisit',
    profileTabs: ['Обо мне', 'Секреты', 'Промо', 'Встречи'],
    requestsTableTitles: {
      location: 'Расположение',
      date: 'Дата',
      time: 'Время',
      published: 'Дата публикации',
      chats: 'Чаты',
      expires: 'Истекает',
      with: 'С кем',
      gift: 'Подарок',
      preferredDateText: 'Желаемая дата',
      preferredTimeText: 'Желаемое время',
    },
    edit: 'Изменить',
    publishAgain: 'Опубликовать еще раз',
    goToChat: 'Перейти в чат',
    alertPhotos: 'Значок глаза показывает видимость фотографии. Общедоступные фотографии отображаются на вашей' +
      ' странице, а частные можно отправить в чате.',
    yourPhotos: 'Ваши фото',
    searchFilters: 'Фильтры поиска',
    save: 'Сохранить',
    expired: 'Истекло',
    startChat: 'Начать чат, чтобы попросить разрешение на просмотр',
    morePrivatePhoto: 'еще 1 приватное фото',
    morePrivatePhotos: 'еще $count приватных фото',
    textFieldLabels: {
      tagline: 'Слоган',
      description: 'Описание',
      comments: 'Комментарии',
      startDate: 'Дата начала',
      date: 'Дата',
      endDate: 'Дата окончания',
      preferredStartTime: 'Время начала',
      preferredEndTime: 'Время окончания',
    },
    textFieldPlaceholders: {
      myHome: 'Мой дом',
      lookingForward: 'С нетерпением жду встречи с тобой!',
      dateRequestTitle: 'Это будет отображаться в списке публикаций в виде заголовка.',
      dateRequestDescription: 'Кратко опишите, чего вы ждете от свидания',
      chatInput: 'Сообщение',
      oldPassword: 'Старый пароль',
      newPassword: 'Новый пароль',
      confirmPassword: 'Повторите пароль',
      phoneNumber: 'Номер телефона'
    },
    textFieldErrorText: {
      required: 'Обязательное поле',
      password: 'Неправильный пароль',
      smthWrong: 'Что-то не так'
    },
    done: 'Готово',
    cancel: 'Отмена',
    editRequests: 'Редактирование промо:',
    deletePromo: 'Удалить промо',
    mainProfilePhoto: 'Главное фото профиля',
    privacyLevel: 'Уровень конфиденциальности',
    privacyLevelOptions: privacyLevelRu,
    descriptionText: 'Описание',
    whenToMeet: 'Когда Вы хотели бы встретиться? Обратите внимание, что вы можете запросить дату не позднее, чем через 1 неделю. Вы можете оставить поле пустым, если для вас это не критично - в этом случае запрос будет действителен в течение 2 недель.',
    publish: 'Опубликовать',
    chatRequest: 'Запрос в чат',
    showPrivatePhotosText: 'Показать личные фотографии',
    shareText: 'Показать',
    photosText: 'фото',
    secretsText: 'секреты',
    wasBlocked: 'был заблокирован',
    wasUnblocked: 'был разблокирован',
    yourDate: 'Ваша встреча',
    offerDate: 'Позвать на свидание',
    selectChat: 'Пожалуйста, выберите чат',
    unblockUserText: 'Разблокировать пользователя',
    blockUserText: 'Блокировать пользователя',
    reportText: 'Пожаловаться',
    deleteChatText: 'Удалить чат',
    deleteText: 'Удалить',
    doYouWantDeleteMsg: 'Вы хотите удалить это сообщение?',
    alsoDeleteFor: 'Также удалить для',
    actionChatAcceptedText: 'Запрос в чат был принят',
    actionChatDeclinedText: 'Запрос в чат был отклонен',
    actionDateOfferAcceptedText: 'Предложение встречи было принято',
    actionDateOfferDeclinedText: 'Предложение встречи было отклонено',
    actionDateOfferCanceledText: 'Встреча была отменена',
    wantsToChat: '$name хочет пообщаться с тобой!',
    accept: 'Принять',
    decline: 'Отклонить',
    dateRequestText: 'Предложение встречи:',
    offersADate: '$name предложил встретиться:',
    youHaveSharedPhotos: 'Вы поделились $photos $and $secrets с $name',
    sharedPrivatePhotosWithYou: '$name поделился $private $photos $and $secrets с вами',
    privateText: 'приватными',
    toMeet: 'Встретиться',
    expectedGift: 'Ожидаемый подарок',
    specifyDecentGift: 'Уточните ценность подарка. Вы можете добавить конкретную сумму (100) или диапазон (100–150)' +
      ' или оставить поле пустым, если вы предпочитаете обсудить это лично.',
    sendOffer: 'Отправить предложение',
    submitReport: 'Отправить жалобу',
    describeWhatWrong: 'Пожалуйста, опишите что случилось:',
    wantToCancelDate: 'Вы уверены что хотите отменить эту встречу?',
    fundsReleasedBack: 'Удерживаемые средства будут возвращены на счет Спонсора.',
    yesCancelDate: 'Да, отменить встречу',
    noCancelDate: 'Нет, не отменять',
    communicateRegarding: 'Пожалуйста, для вашей безопасности сообщайте о свидании только в чате Lay и встречайтесь в назначенное вами время.',
    cancelDateText: 'Отменить встречу',
    saveChanges: 'Сохранить изменения',
    reset: 'Сбросить',
    apply: 'Применить',
    sentChatRequest: 'Вы отправили запрос в чат. $displayName проверит его и либо примет, либо отклонит. Это может' +
      ' занять некоторое время. А пока вы можете отправить запросы в чат другим людям.',
    privatePhotoCaption: 'Никто не видит это фото на вашей странице. Вы можете раскрыть это лично в чате',
    publicPhotoCaption: 'Все пользователи могут видеть это фото на вашей странице',
    age: 'Возраст',
    changePasswordText: 'Изменить пароль',
    changeLanguageText: 'Сменить язык',
    noPromoTitle: 'Промо пока не добавлены',
    noPromoText: 'Сообщите людям, когда и где вы хотели бы встретиться, и мы\n' +
      'покажем это объявление другим бесплатно!',
    noPromoBtnText: 'Круто! Попробовать сейчас',
    noDatesTitle: 'Свиданий пока нет',
    noDatesText: 'Здесь мы перечислим все ваши прошлые и будущие свидания, чтобы вы ничего не пропустили!',
    noDatesBtnText: 'Найти кого-нибудь для свидания',
    getCode: 'Получить код',
    typeCode: 'Введите код',
    enable: 'Включить',
    disable: 'Отключить',
    successText: 'Успешно',
    mfaText: 'Двухфакторная аутентификация',
    disableMfa: 'Отключить двухфакторную аутентификацию',
    enableMfa: 'Включить двухфакторную аутентификацию',
    noSelectedPhotos: 'Вы не выбрали ни одной фотографии',
    returnText: 'Вернуться',
    rowsPerPageText: 'Строк на странице',
    ofText: 'из',
    photosDestroyedText: 'Фотографии будут уничтожены через $count секунд',
    fewDetails: 'Больше никаких данных о $displayName! Напиши в чат, чтобы узнать больше.',
    soEmpty: 'Твоя страница такая пустая! Может, стоит добавить чуть больше деталей о себе?',
    emptyChatsText: 'Кажется, у тебя пока нет чатов! Вот тут у нас $search - можешь найти кого-нибудь и написать.' +
      ' Или $add и пусть пишут тебе первыми!',
    searchChatText: 'поиск людей',
    addPromoChatText: 'добавь своё промо',
    noPhotoTitleText: 'Ни одной фотографии?',
    noPhotoText: 'Если не хочешь «светить» свои реальные фотографии, на Lay ты можешь добавить их в приватном режиме. Никто не увидит их, пока ты лично не откроешь их человеку в чате, и вскоре после этого они исчезнут из чата автоматически.',
    noPhotoBtnText: 'ОК, добавлю пару фото!',
    JustOnePhoto: 'Всего одна фотография?',
    JustOnePhotoBtnText: 'ОК, добавлю больше фото!',
    peopleInCity: 'Люди в твоем городе',
    seeMoreText: 'Увидеть больше',
    backToProfile: 'Назад в профиль'
  },
  lv: {
    clarification: "Apmaksātais iepazīšanās pakalpojums no 2022",
    signIn: "Lelogoties",
    signUp: "Pierakstīties",
    paidService: "Apmaksāta datēšana pastāvēja pirms Ēģiptes piramīdām. Tā pastāvēs pēc 8. pasaules kara, kas 5042. gadā nogalināja 90% pasaules iedzīvotāju.",
    weAreWorking: "Mēs strādājam pie tā, lai šis pakalpojums būtu ideāls un būs gatavs palaišanai 2021 gada sākumā. Kļūstiet par mūsu agrīno dalībnieku un saņemiet jauku prēmiju!",
    addYourProfile: "Pievienojiet savu profilu",
    inventIt: "Mēs to neizdomājām.",
    weMadeItTransparent: "Mēs to padarījām caurspīdīgu, drošu un patīkamu.",
    wantToGetPartner: "Vai vēlaties atrast partneri drošai un izdevīgai lietai?",
    menWantToGetPartner: "Jūs gribat pie atrast meiteni for viegla datēšana?",
    iLookingFor: "ES meklēju",
    howItWorkedBefore: "Kā tas darbojās iepriekš",
    lookingForAPartner: "Meklējat partneri “normālā” iepazīšanās platformā",
    struggleWithShyness: "Cīņa ar kautrību",
    tryToFilter: "Mēģiniet filtrēt 80% no krāpšanās piedāvājumiem",
    hopeThat: "Ceru, ka šis puisis vai meitene patiešām izskatās šādi",
    tryYourBest: "Centieties, lai jūs netiktu aizliegts",
    or: "vai",
    browseUnpleasantWebsites: "Pārlūkojiet nepatīkamas vietnes 90. gadu stilā",
    messWithShadyGuys: "Haoss ar ēnainiem puišiem",
    thatThePhotosAreReal: "Pat neceriet, ka fotogrāfijas ir reālas",
    neverSeeYourPartner: "Nekad neredzi savu partneri pirms tikšanās",
    workWithCash: "Strādājiet ar skaidru naudu un lūdziet, lai jūs izkļūtu tur droši",
    howItWorksOn: "Kā tas darbojas uz",
    allUsersHaveClearIntentions: "Visiem lietotājiem ir skaidri nodomi, un viņi neapmaldīs",
    noEscort: 'Nekādas eskorta aģentūras un viltojumi, tikai reālas meitenes from Latvija',
    uploadedPhotosAreVerified: "Augšupielādētie fotoattēli ir verificēti",
    yourIdentity: "Jūsu identitāte nekad netiek atklāta sabiedrībai",
    decideWhomToChatWith: "Izlemiet, ar ko tērzēt",
    hideYourPhotos: "Paslēpt savus fotoattēlus un parādīt atlasītajiem lietotājiem",
    payAndGetPaid: "Droši maksājiet un saņemiet samaksu, izmantojot bankas karti",
    joinLayNow: "Pievienojies gulēšanai tūlīt! ",
    faq: "FAQ",
    comingSoon: "Drīzumā",
    paidDatingService: "Apmaksāts iepazīšanās pakalpojums",
    welcomeToLay: 'Laipni lūdzam Lay!',
    signInWithGoogle:'Pierakstīties ar Google',
    submitYourEmail:'Iesniedziet savu e-pastu',
    emailIsIncorrect: 'E-pasts nav pareizs',
    emailAlreadyInUse: 'E-pasts jau tiek izmantots',
    createPasswordLabel: 'Izveidot paroli',
    wrongPassword: 'Nepareiza parole',
    tooManyRequests: 'Pārāk daudz pieprasījumu',
    userNotFound: 'Lietotājs nav atrasts',
    createPasswordErrorText: 'Parolei jābūt vismaz 1 mazajam leer, 1 lielajam burtam, 1 ciparam un kopā vismaz 8 simbolus',
    confirmPasswordsLabel:'Apstiprināt paroles',
    confirmPasswordsError: 'Paroles nesakrīt',
    continueButton: 'Turpināt',
    bySigningUpIAgreeTo: 'Reģistrējoties, es piekrītu šādiem dokumentiem:',
    termsOfService: 'pakalpojumu sniegšanas noteikumi',
    privacyPolicy: 'privātuma politika',
    and: 'un',
    alreadyGotAnAccount: 'Vai jums jau ir konts?',
    logIn: 'Pieslēgties',
    welcomeBack: 'Laipni lūdzam atpakaļ!',
    emailLabel: 'E-pasts',
    passwordLabel: 'Parole',
    incorrectUsernameOrPassword: 'Nepareizs lietotājvārds vai parole',
    forgotPassword: 'Aizmirsi paroli?',
    submitYourEmailText: 'Lesniedziet savu e-pastu, mēs nosūtīsim jums saiti, lai atjaunotu paroli',
    sentAResetPassword: 'Mēs esam nosūtījuši saiti uz paroles atiestatīšanu uz',
    proceedToYourInbox: 'Lūdzu, dodieties uz iesūtni.',
    chooseYourRole: 'Lūdzu, izvēlieties savu lomu Lay',
    patronLabel: 'Sponsor',
    patronText: 'Jūs apbalvosiet izlasi par tikšanos.',
    favoriteLabel: 'Izlase',
    favoriteText: 'Sponsori atalgos par sapulcēm.',
    thankYou: 'Paldies, ka pievienojāt savu skaisto profilu vietnē Lay',
    thankYouText: 'Mēs cītīgi strādājam, lai padarītu šo pakalpojumu drošu un ērtu. Tiklīdz mēs būsim gatavi sākt, mēs sazināsimies ar jums pa e-pastu un nosūtīsim jums bonusu.',
    layTeam: 'Jūsu, Lay komanda',
    success: 'Panākumi!',
    confirmYourEmail: 'Lūdzu, dodieties uz iesūtni un apstipriniet, ka jūsu e-pasts noklikšķina uz saites, kuru mēs jums nosūtījām.',
    sendAgainText: 'Didn\'t receive the Email?',
    sendAgainTextCaption: 'E-pasta ziņojumi parasti tiek piegādāti 1-2 minūšu laikā, bet piegāde var ilgt līdz 5 minūtēm. Tāpat, lūdzu, pārbaudiet savu Spam mapi, pārbaudes e-pastus var būt tur. Ja jums ir kādas problēmas, sazinieties ar mums, izmantojot support@lay.ooo',
    sendAgainLink: 'Send it Again',
    personalInformation: 'Personīgā informācija',
    personalInfoTitles: titlesLv,
    personalInfoPlaceholders: placeholdersEn,
    submitPersonalNumber: 'YJūsu tālruņa numurs nebūs redzams citiem lietotājiem. Tas ir nepieciešams, lai verificētu jūsu profilu. Lūdzu, iesniedziet savu personīgo numuru.',
    addPersonalNumber: 'Lūdzu, pievienojiet savu tālruņa numuru. Tas nekad <strong>nebūs</strong> pieejams Lay' +
      ' lietotājiem. Administratoriem tas ir nepieciešams, lai pārbaudītu jūsu profilu, bet <strong>nekad to' +
      ' nevienam</strong> neatklāj. Mēs augstu vērtējam jūsu privātumu un tajā pašā laikā ir nepieciešams visiem Lay lietotājiem ir reāli cilvēki.',
    yourPhoneIsProtected: 'Jūsu tālruņa numuru aizsargā Vispārīgā datu aizsardzības regula (VDAR), kas ir Eiropas Savienības tiesību aktu regula. Jūs varat pieprasīt pilnīgu visas jūsu personiskās informācijas dzēšanu lay sazinoties ar mums support@lay.ooo.',
    completeMandatoryField: 'Obligāts lauks. Lūdzu, aizpildiet',
    displayNameLengthError: 'Minimālais vārda garums ir 2 simboli, tiek pieņemti tikai burti',
    phoneNumberIsNotCorrect: 'Tālruņa numurs nav pareizs',
    dateIsNotCorrect: 'Gulēja nav paredzēti tiem, kas ir jaunāki par 18 gadiem',
    countries: countriesEn,
    next: 'Nākamais',
    submit: 'Lesniegt',
    tellAboutYourself: 'Pastāsti citiem cilvēkiem par sevi. Visi lauki nav obligāti, pagaidām varat to izlaist un pievienot vēlāk. Lūdzu, nelietojiet stingru valodu un neatstājiet kontaktpersonas (tālruni, e-pastu, vietni, kurjera ID, adresi). Pretējā gadījumā jūsu konta darbība tiks apturēta.',
    tellAboutYourSecrets: 'Pastāstiet cilvēkiem par saviem noslēpumiem. Šī informācija nav publiska: jums būs jāatslēdz šī sadaļa jūsu profilā personīgi tērzēšanā.',
    secretsAlert: 'Informācija no šīs iedaļas nebūs publiski pieejama. <strong>Neviens</strong> redzēs to Lay mājas' +
      ' lapā.',
    photoAlert: 'Jūs varat padarīt jūsu fotogrāfijas privāti, lai neviens redzēs jūsu profila lapā Lay.',
    whyAddPhoto: 'Kāpēc pievienot fotogrāfijas? Lai palielinātu jūsu izredzes uz veiksmīgu datumu 🙂 76% $gender Lay' +
      ' pievienot fotogrāfijas par sevi - viņu profili tiek apskatīti biežāk un vairāk cilvēku sāk tērzēšanu ar' +
      ' tiem. Ja jūs nevēlaties atklāt savu personību, vienkārši izvēlieties <strong>Private</strong> iespēju. Šajā gadījumā' +
      ' citi redzēs, ka jums ir privātas fotogrāfijas, un lūgs jūsu atļauju tos skatīt Lay Chat. Pēc tam izlemiet, vai vēlaties piešķirt piekļuvi vai 😉',
    addInfoAboutYourSecrets: 'Pievienot informāciju par jūsu dzimuma vēlmēm, dāvanu cerības un ceļojumu' +
      ' opportunitites. Tas <strong>netiks rādīts</strong> jūsu profila lapā lay. Jūs varēsiet atvērt šo sadaļu' +
      ' citai personai' +
      ' privāti <strong>Lay Chat</strong>. Tam būs īpaša poga.',
    whyAddInfoAboutYourSecrets: 'Kāpēc pievienot šo anyway? Jūsu nākotnes ērtības 🙂 Šie jautājumi ir diezgan bieži uzdoti, un kam tas viss stuff vienā vietā, kas spēj dalīties ar 1 klikšķi būs tikai padarīt jūsu dzīvi vieglāku. Nav bezjēdzīgi sarunas un pašas lietas paskaidrots atkal un atkal. Jums būs iespēja rediģēt šo jebkurā laikā.',
    noteThatBeforeModerator: 'Lūdzu, ņemiet vērā, ka pirms moderators pieņem jūsu profila fotoattēlus, jūs nevarēsit tērzēt ar citiem lietotājiem. Lai gan jūs varat atzīmēt savus fotoattēlus kā privātus, un tie netiks rādīti publiski. Varat arī ierobežot, lai tos redzētu tikai moderatori. Tie būs jāatbloķē lietotājiem personīgi tērzēšanā.',
    uploadUpPhotos: 'Augšupielādējiet līdz pat 10 fotoattēliem reālajā dzīvē. Pārliecinieties, ka vismaz viens no šiem fotoattēliem ir jūsu seja skaidri redzams - tas ir nepieciešams pārbaudei. Ja vēlaties, jūs varat ierobežot publisku piekļuvi fotoattēliem ar seju. Nude fotoattēli ir labi, bet jūs nevarat tos publiskot',
    addPhoto: '+ Pievienot fotoattēlu',
    addLink: '+ + Pievienot saiti',
    pasteLinks: 'Ielīmējiet saites uz Youtube, Instagram, Tik Tok vai Twitter videoklipiem. Plika videoklipi ir aizliegti.',
    photosTitle: 'Fotoattēli',
    videosTitle: 'Video',
    tabsTitles: [
      {
        label: '1. Galvenais',
        disabled: false
      },
      {
        label: '2. Par tevi',
        disabled: false
      },
      {
        label: '3. Noslēpumi',
        disabled: false
      },
      {
        label: '4. Fotoattēli',
        disabled: false
      },
    ],
    citiesTitles: citiesEn,
    genderOptions: genderOptionsLv,
    lookingForOptions: lookingForOptionsLv,
    languagesOptions: languagesOptionsLv,
    figureOptions: figureOptionsLv,
    ethnicityOptions: ethnicityOptionsLv,
    hairOptions: hairOptionsLv,
    eyesOptions: eyesOptionsLv,
    areaAvailabilityOptions: areaAvailabilityOptionsLv,
    faqList: faqLv,
    faqMenList: faqMenLv,
    modalPhoneTitle: 'Šķiet, ka esat aizmirsis atstāt tālruni',
    modalPhoneBtnLeft: 'Turpiniet bez tālruņa',
    modalPhoneBtnRight: 'Atgriezieties un atstājiet tālruni',
    modalPhoneContent: ['Žēl, ka vēlaties reģistrēties, nenorādot savu tālruņa numuru. Mēs nevarēsim pārliecināties,' +
    ' ka esat reāls cilvēks.', 'Kas notiks tagad? Profili, kas reģistrēti bez tālruņa, lietotājiem tiks rādīti retāk' +
    ' nekā pārbaudīti profili. 72% no Lay lietotājiem norāda numuru, un 28% neapstiprināto profilu būs saraksta' +
    ' pašās beigās 🙁', 'Ko var darīt? Pievienojiet savu tālruni 🙂 Vai arī nākamajā solī vismaz pievienojiet vienu vai vairākus fotoattēlus - profili ar fotoattēliem, pat ja tie ir privāti un paslēpti no visiem, būs augstāki nekā profili, kuros nav tālruņa vai fotoattēla.'],
    editForm: 'Rediģēt profilu',
    termsConditionsTitle: 'TERMS AND CONDITIONS OF USE',
    termsConditionsList: termsConditionsEn,
    safetyTipsTitle: 'DATING SAFETY TIPS',
    safetyTipsList: safetyTipsEn,
    safetyPolicyTitle: 'SAFETY POLICY TERMS AND CONDITIONS',
    safetyPolicyList: safetyPolicyEn,
    intellectualPropertyTitle: 'INTELLECTUAL PROPERTY TERMS',
    intellectualPropertyList: intellectualPropertyEn,
    cookiePolicyTitle: 'COOKIE POLICY',
    cookiePolicyList: cookiePolicyEn,
    firstChatPopupTitle: 'Pirms sākat tērzēt ...',
    firstChatPopupFirstText: 'Mēs uzturam draudzīgu vidi Lay un neļaujam lietotājiem būt rupjiem vienam pret otru. Lūdzu, cieniet pārējos un runājiet pieklājīgi. Paturiet prātā, ka tērzēšanā ir poga Ziņot, kuru var izmantot abas tērzēšanas puses. Mūsu komanda izskatīs visus ziņojumus un mums būs jāaizliedz tie, kas pārkāpj noteikumus. Ceru, ka ar jums tas nekad nenotiks',
    firstChatPopupSecondText: 'Mīlestība, Lay komanda',
    firstChatPopupButton: 'Labi, sapratu!',
    firstChatPopupMessagesTitle: 'Laipni lūdzam savā pirmajā tērzēšanā!',
    firstChatPopupMessagesFirstText: 'Pārbaudiet 3 punktu pogu labajā pusē. Tur jūs varat:',
    firstChatPopupMessagesOptions: ['Bloķēt vai atskaitīt lietotāju', 'Izdzēsiet tērzēšanu'],
    firstChatPopupMessagesPs: 'PS: Ja jūs nolemjat tikties viens ar otru, lūdzu, neaizmirstiet «piedāvāt datumu» vai pieņemt piedāvājumu. Šajā gadījumā mēs varēsim jums palīdzēt, ja jums ir pārpratumi.',
    notApprovedPopupTitle: 'Paldies par reģistrāciju uz Lay!',
    notApprovedPopupText: 'Tagad jūsu profils tiek pārskatīts mūsu administratori, un citi lietotāji jūs neredzēs. Lai gan apstiprinājums notiek, jūs varat izmantot meklēšanu un redzēt citus cilvēkus. Pēc tam, kad mēs apstiprinām jūs, jūsu profils kļūst redzams citiem. Jūs arī varēsiet sazināties ar cilvēkiem un publicēt promos par sevi bez maksas. Mēs jums paziņosim pa e-pastu!',
    dialogOptions: {
      block : {
        head: 'Vai tu esi pārliecināts?',
        content: 'Pēc bloķējot $displayName nevarēs jums ziņas, un jūs nevarēsiet atbildēt. Jūs varēsiet atbloķēt šo' +
          ' personu nākotnē.',
        leftBtnText: 'Jā',
        rightBtnText: 'Atcelt'
      },
      report : {
        head: 'Vai tu esi pārliecināts?',
        content: 'Pēc šī ziņojuma saņemšanas mūsu atbalsta komanda to pārskatīs, sazināsies ar jums un, iespējams, bloķētu $displayName.',
        leftBtnText: 'Jā',
        rightBtnText: 'Atcelt'
      },
      remove : {
        head: 'Vai tu esi pārliecināts?',
        content: 'Visa jūsu ziņojumapmaiņas vēsture tiks noņemta, un jūs nevarēsiet to atjaunot.',
        leftBtnText: 'Jā',
        rightBtnText: 'Atcelt'
      },
    },
    location: locationOptionsLv,
    adaptiveLocation: adaptiveLocationOptionsLv,
    whyLocation: 'Ļaujiet cilvēkiem uzzināt, kur jūs plānojat tos satikt. Jūs varat izvēlēties vairākas iespējas.',
    roles: {
      title: 'Vai tu esi pārliecināts?',
      leftBtnText: 'Jā, es esmu pārliecināts 😉',
      rightBtnText: 'Ak, nē',
      content: 'Programmā Lay mēs pilnībā iestājamies par dzimumu līdztiesību, bet tikai jūsu informēšanai: 96% vīriešu, kas reģistrējušies, izvēlas sponsora lomu, bet 97% meiteņu izvēlas izlases lomu. Kā izlasi jūs redzēsiet galvenokārt vīriešus, kuri meklē apmaksātus randiņus ar meitenēm.'
    },
    deletePopup: {
      title: 'Vai tu esi pārliecināts?',
      leftBtnText: 'Jā, es esmu pārliecināts',
      rightBtnText: 'Ak, nē'
    },
    profileNavTitles: ['Profils', 'Meklēt сilvēki', 'Tērzēšana', 'Meklēšanas datumi'],
    addADateRequest: 'Pievienojiet datuma pieprasījumu',
    profileOptions: ['Publicējiet datuma pieprasījumu', 'Rediģēšanas profilu', 'Atteikšanos', 'Iestatījumi'],
    chatNow: 'Čats tagad',
    lastVisitText: 'Pēdējais redzējis $lastVisit',
    profileTabs: ['Par mani', 'Noslēpumi', 'Datuma pieprasījumi', 'Datumi'],
    requestsTableTitles: {
      location: 'Atrašanās vieta',
      date: 'Datums',
      time: 'Laiks',
      published: 'Publicēts',
      chats: 'Tērzēšana',
      expires: 'Beidzas',
      with: 'Ar',
      gift: 'Dāvana',
      preferredDateText: 'Vēlamais datums',
      preferredTimeText: 'Vēlamais laiks',
    },
    edit: 'Rediģēt',
    publishAgain: 'Publicēt vēlreiz',
    goToChat: 'Let uz tērzēšanu',
    alertPhotos: 'Acu ikona parāda foto redzamību. Publiskās fotogrāfijas tiek parādītas jūsu lapā, kamēr privātā tiek atklāta manuāli tērzēšanā.',
    yourPhotos: 'Tavas fotogrāfijas',
    searchFilters: 'Meklēt filtrus',
    save: 'Saglabāt',
    expired: 'Beidzies derīguma termiņš',
    startChat: 'Sāciet tērzēšanu, lai lūgtu atļauju apskatīt',
    morePrivatePhoto: '1 vairāk privātā foto',
    morePrivatePhotos: '$count vairāk privāto fotogrāfiju',
    textFieldLabels: {
      tagline: 'Tagline',
      description: 'Apraksts',
      comments: 'Komentāri',
      startDate: 'Sākuma datums',
      date: 'Datums',
      endDate: 'Beigu datums',
      preferredStartTime: 'Vēlamais sākuma laiks',
      preferredEndTime: 'Vēlamais beigu laiks',
    },
    textFieldPlaceholders: {
      myHome: 'Manas mājas',
      lookingForward: 'Ceram satikties ar jums!',
      dateRequestTitle: 'Tas tiks parādīts datuma sarakstā kā nosaukums',
      dateRequestDescription: 'Īsi aprakstiet, ko jūs sagaidāt no datuma',
      chatInput: 'Ierakstiet savu ziņojumu šeit',
      oldPassword: 'Vecā parole',
      newPassword: 'Jauna parole',
      confirmPassword: 'Atkārtojiet jaunu paroli',
      phoneNumber: 'Telefona numurs'
    },
    textFieldErrorText: {
      required: 'Obligāts lauks',
      password: 'Nepareiza parole',
      smthWrong: 'Something wrong'
    },
    done: 'Gatavs',
    cancel: 'Atcelt',
    editRequests: 'Rediģēt promo:',
    deletePromo: 'Dzēst promo',
    mainProfilePhoto: 'Galvenā profila fotoattēls',
    privacyLevel: 'Privātuma līmenis',
    privacyLevelOptions: privacyLevelLv,
    descriptionText: 'Apraksts',
    whenToMeet: 'Kad jūs vēlētos tikties? Ņemiet vērā, ka jūs varat pieprasīt datumu ne vēlāk kā 1 nedēļu no šī brīža. Jūs varat atstāt to tukšu, ja tas nav kritisks jums - šajā gadījumā pieprasījums būs derīgs 2 nedēļas no šī brīža.',
    publish: 'Publicēt',
    chatRequest: 'Tērzēšanas pieprasījums',
    showPrivatePhotosText: 'Rādīt privātās fotogrāfijas',
    shareText: 'Koplietojiet',
    photosText: 'fotoattēlus',
    secretsText: 'noslēpumi',
    wasBlocked: 'tika bloķēts',
    wasUnblocked: 'bija atbloķēts',
    yourDate: 'Jūsu datums',
    offerDate: 'Piedāvājums datums',
    selectChat: 'Lūdzu, izvēlieties tērzēšanu',
    unblockUserText: 'Atbloķēt lietotājam',
    blockUserText: 'Bloķēt lietotāju',
    reportText: 'Ziņot',
    deleteChatText: 'Dzēst tērzēšanu',
    deleteText: 'Izdzēst',
    doYouWantDeleteMsg: 'Vai vēlaties dzēst šo ziņojumu?',
    alsoDeleteFor: 'Arī dzēst',
    actionChatAcceptedText: 'Tika pieņemts tērzēšanas pieprasījums',
    actionChatDeclinedText: 'Tika noraidīts tērzēšanas pieprasījums',
    actionDateOfferAcceptedText: 'Datuma piedāvājums tika pieņemts',
    actionDateOfferDeclinedText: 'Datuma piedāvājums tika noraidīts',
    actionDateOfferCanceledText: 'Datuma piedāvājums tika atcelts',
    wantsToChat: '$name vēlas tērzēt ar jums!',
    accept: 'Pieņemt',
    decline: 'Kritums',
    dateRequestText: 'Datuma pieprasījums:',
    offersADate: '$name piedāvā datumu:',
    youHaveSharedPhotos: 'Jums ir koplietojušās $photos $and $secrets ar $name',
    sharedPrivatePhotosWithYou: '$name koplietojiet $private $photos $and $secrets us ar jums',
    privateText: 'privātās',
    toMeet: 'Satikt',
    expectedGift: 'Paredzamā dāvana',
    specifyDecentGift: 'Norādiet, kāda ir pienācīga dāvana. Jūs varat pievienot noteiktu summu (100) vai diapazonu (100-150) vai atstāt to tukšu, ja vēlaties to apspriest personīgi.',
    sendOffer: 'Sūtīt piedāvājumu',
    submitReport: 'Lesniegt ziņojumu',
    describeWhatWrong: 'Lūdzu, aprakstiet, kas ir nepareizi:',
    wantToCancelDate: 'Vai esat pārliecināts, ka vēlaties atcelt šo datumu?',
    fundsReleasedBack: 'Turētie līdzekļi tiks atbrīvoti atpakaļ uz sponsora kontu.',
    yesCancelDate: 'Jā, atcelt datumu',
    noCancelDate: 'Nē, nav atcelt',
    communicateRegarding: 'Lūdzu, par savu drošību, paziņojiet par savu datumu, lai tērzētu tikai un tikties brīdī, par kuru jūs piekritis.',
    cancelDateText: 'Atcelt datumu',
    saveChanges: 'Saglabāt izmaiņas',
    reset: 'Atiestatīt',
    apply: 'Piesakies',
    sentChatRequest: 'Jūs nosūtījāt tērzēšanas pieprasījumu. $displayName nosaukums pārskatīs to un vai nu pieņems' +
      ' vai noraidīs. Tas var aizņemt kādu laiku. Tikmēr jūs varētu vēlēties nosūtīt vairāk tērzēšanas pieprasījumu ar citiem cilvēkiem',
    privatePhotoCaption: 'Neviens redz šo fotoattēlu jūsu lapā. Jūs varat to atklāt personīgi tērzēšanā',
    publicPhotoCaption: 'Visi lietotāji var redzēt šo fotoattēlu savā lapā',
    age: 'Vecums',
    changePasswordText: 'Mainīt paroli',
    changeLanguageText: 'Mainīt valodu',
    noPromoTitle: 'Līdz šim nav pievienots neviens promo',
    noPromoText: 'Ļaujiet cilvēkiem uzzināt, kad un kur jūs vēlētos tikties un mēs parādiet šo reklāmu citiem bez' +
      ' maksas!',
    noPromoBtnText: 'Atdzist! Mēģiniet tagad',
    noDatesTitle: 'Līdz šim nav datumi',
    noDatesText: 'Mēs uzskaitīsim visas jūsu pagātnes un nākotnes datumus, lai jūs nekad garām kaut ko garām!',
    noDatesBtnText: 'Iet atrast kādu līdz šim',
    getCode: 'lai iegūtu kodu',
    typeCode: 'Ievadiet kodu',
    enable: 'Iespējot',
    disable: 'Atspējot',
    successText: 'Panākumi',
    mfaText: 'Daudzfaktoru autentifikācija',
    disableMfa: 'Atspējot daudzfaktoru autentifikāciju',
    enableMfa: 'Iespējot daudzfaktoru autentifikāciju',
    noSelectedPhotos: 'Jūs neesat izvēlējies fotoattēlus',
    returnText: 'Atgriešanās',
    rowsPerPageText: 'Rindas vienā lapā',
    ofText: 'no',
    photosDestroyedText: 'Fotogrāfijas tiks iznīcinātas $count sekundēs',
    fewDetails: '$displayName nav pievienojis sīkāku informāciju. Jūtieties brīvi jautāt tērzēšanā!',
    soEmpty: 'Jūsu lapa izskatās tik tukša! Apsveriet iespēju pievienot sīkāku informāciju',
    noPhotoTitleText: 'Nav fotogrāfiju vispār?',
    noPhotoText: 'Ja jūs nevēlaties koplietot savas reālās fotogrāfijas, neuztraucieties. Uzklājiet tos varat pievienot tos privātajā režīmā. Neviens neredzēs tos, līdz jūs tos kopīgat ar konkrētu personu tērzēšanā. Neilgi pēc tam, ka privātās fotogrāfijas tiek automātiski izņemti no tērzēšanas.',
    noPhotoBtnText: 'Labi, pievienojiet pāris fotogrāfijas!',
    JustOnePhoto: 'Tikai viens fotoattēls?',
    JustOnePhotoBtnText: 'Labi, pievienojiet vairāk fotoattēlu!',
    peopleInCity: 'Cilvēki jūsu pilsētā',
    seeMoreText: 'Redzēt vairāk',
    backToProfile: 'Atpakaļ uz profilu'
  }
};

export {localisation};
